var MSG = {
  title: "BlocklyPEN",
  blocks: "ブロック",
  linkTooltip: "ブロックの状態を保存してリンクを取得します。",
  runTooltip: "ブロックで作成したプログラムを実行します。",
  badCode: "プログラムのエラー:\n%1",
  timeout: "命令の実行回数が制限値を超えました。",
  trashTooltip: "すべてのブロックを消します。",
  catCompLogic: "比較・論理",
  catControl: "制御",
//  catLogic: "条件分岐",
//  catLoops: "繰り返し",
  catInoutput: "入出力",
  catdeclaratation: "宣言",
  catValue: "値",
  catVariable: "変数",
//  catnum: "値",
  catMath: "計算",
  catSamples: "サンプル",
  catText: "文字",
  catgwindow: "窓操作",
  catgset: "描画設定",
  catgdraw: "描画",
  catfile: "ファイル",
  catFunctions: "関数",
  listVariable: "リスト",
  textVariable: "テキスト",
  // httpRequestError: "ネットワーク接続のエラーです。",
  // linkAlert: "ブロックの状態をこのリンクで共有できます:\n\n%1",
  // hashError: "すみません。「%1」という名前のプログラムは保存されていません。",
  // xmlError: "保存されたファイルを読み込めませんでした。別のバージョンのブロックリーで作成された可能性があります。",
  // badXml: "XML のエラーです:\n%1\n\nXML の変更をやめるには「OK」、編集を続けるには「キャンセル」を選んでください。"
};
